name: Generar API de Rayos

on:
  schedule:
    # Se ejecuta cada 5 minutos
    - cron: '*/5 * * * *'
  workflow_dispatch: # Permite la ejecución manual

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar script para generar datos
        run: node generar_api.js

      - name: Hacer commit de los cambios
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add api/datos_rayos.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Actualización automática de datos de rayos" && git push)